# It's a dummy config, for unit test only!!!

# database :
#   hostname :
#   username :
#   password :
#   database :
# mysql :
#   hostname : hao-dev-infra01.eastus.cloudapp.azure.com
#   port : 3306
#   username : root
#   password : MSFT1234!
# kubelet-path : /usr/local/bin/kubectl
storage-mount-path : /dlwsdata
# root-path : /DLWorkspace/src/
root-path : ".." # for unittest only
# nvidiaDriverPath : /opt/nvidia-driver/current
# clusterId : b6815f6d-612c-4feb-a8f3-bc7ceaa43993
# domain : eastus.cloudapp.azure.com
# apiserver: https://hao-dev-infra01.eastus.cloudapp.azure.com:1443
# certificate-authority: /etc/kubernetes/ssl/ca.pem
# client-certificate: /etc/kubernetes/ssl/apiserver.pem
# client-key: /etc/kubernetes/ssl/apiserver-key.pem
# pod_ip_range: 10.2.0.0/16
# per_user_gpu_limit: -1
rest-api: http://faked.uri/
# usefreeflow: False
# mountdescription : {'hdfs': 'Hadoop file system (replicated distribute storage).', 'azurefileshare': 'Azure file storage', 'localHDD': 'Local HDD. ', 'glusterfs': 'GlusterFS (replicated distributed storage)', 'nfs': 'NFS (remote file share)', 'emptyDir': 'Kubernetes emptyDir (folder will be erased after job termination).', 'local': 'Local SSD. '}
# mountpoints : {'rootshare': {'curphysicalmountpoint': '/mntdlws/nfs', 'mountpoints': '', 'server': '192.168.255.1', 'type': 'nfs', 'filesharename': '/data/share'}}
# mounthomefolder : yes
# deploymounts : []
# default-storage-folders : ['jobfiles', 'storage', 'work', 'namenodeshare']
# webportal_node: hao-dev-infra01.eastus.cloudapp.azure.com
# datasource : MySQL
# kube_custom_scheduler: False
# WinbindServers: []
